/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Color: (typeof import('./../components/color/index.vue'))['default']
    ProductCard: (typeof import('./../components/product-card/index.vue'))['default']
    Result: (typeof import('./../components/result/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Thumbnail: (typeof import('./../components/thumbnail/index.vue'))['default']
    Trend: (typeof import('./../components/Trend/index.vue'))['default']
  }
}
